### ISSUE TITLE
predict.py 실행 불가

### ISSUE THREAD

**Issue by beopst** [woans0104/lung-seg-back-up#1]
https://github.com/woans0104/lung-seg-back-up/blob/3db86dea7aca4c70342ad1be3f4a4fb3a6194cf1/predict.py#L101

학습 끝난 모델로 predict.py만 실행하면 여기 `npy_file`이 빈 list로 나오면서 에러가 나네요.

**Comment by woans0104** [comment]
혹시 이 부분의 train-size가 1로 되어있지 않나요...
저 npy가 소스 dataset의 test dataset들을 담고 있는 거여서 아래 코드에 train_size가 1로 되어 있다면 npy가 생성이 안될 것입니다..
코드 수정 후 1에서 args.train_size로 바꾸었습니다.

https://github.com/woans0104/lung-seg-back-up/blob/e14a98bc54be5defe8a013408efcff467387e4fb/main_proposed_embedding.py#L99-L102
